# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.mock_server_pb2 as mock__server__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mock_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CountSignalsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Count = channel.unary_unary(
                '/CountSignals/Count',
                request_serializer=mock__server__pb2.ListOfSignals.SerializeToString,
                response_deserializer=mock__server__pb2.DictOfSignals.FromString,
                _registered_method=True)


class CountSignalsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountSignalsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Count': grpc.unary_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=mock__server__pb2.ListOfSignals.FromString,
                    response_serializer=mock__server__pb2.DictOfSignals.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CountSignals', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CountSignals', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CountSignals(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CountSignals/Count',
            mock__server__pb2.ListOfSignals.SerializeToString,
            mock__server__pb2.DictOfSignals.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FireAlarmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckTemperature = channel.unary_unary(
                '/FireAlarm/CheckTemperature',
                request_serializer=mock__server__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=mock__server__pb2.StatusResponse.FromString,
                _registered_method=True)


class FireAlarmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FireAlarmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTemperature,
                    request_deserializer=mock__server__pb2.TemperatureRequest.FromString,
                    response_serializer=mock__server__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FireAlarm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FireAlarm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FireAlarm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FireAlarm/CheckTemperature',
            mock__server__pb2.TemperatureRequest.SerializeToString,
            mock__server__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
