# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mock_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mock_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mock_server.proto\")\n\x12TemperatureRequest\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\rListOfSignals\x12\x0f\n\x07signals\x18\x01 \x03(\t\"g\n\rDictOfSignals\x12(\n\x05\x63ount\x18\x01 \x03(\x0b\x32\x19.DictOfSignals.CountEntry\x1a,\n\nCountEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\x37\n\x0c\x43ountSignals\x12\'\n\x05\x43ount\x12\x0e.ListOfSignals\x1a\x0e.DictOfSignals2E\n\tFireAlarm\x12\x38\n\x10\x43heckTemperature\x12\x13.TemperatureRequest\x1a\x0f.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mock_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DICTOFSIGNALS_COUNTENTRY']._loaded_options = None
  _globals['_DICTOFSIGNALS_COUNTENTRY']._serialized_options = b'8\001'
  _globals['_TEMPERATUREREQUEST']._serialized_start=21
  _globals['_TEMPERATUREREQUEST']._serialized_end=62
  _globals['_STATUSRESPONSE']._serialized_start=64
  _globals['_STATUSRESPONSE']._serialized_end=96
  _globals['_LISTOFSIGNALS']._serialized_start=98
  _globals['_LISTOFSIGNALS']._serialized_end=130
  _globals['_DICTOFSIGNALS']._serialized_start=132
  _globals['_DICTOFSIGNALS']._serialized_end=235
  _globals['_DICTOFSIGNALS_COUNTENTRY']._serialized_start=191
  _globals['_DICTOFSIGNALS_COUNTENTRY']._serialized_end=235
  _globals['_COUNTSIGNALS']._serialized_start=237
  _globals['_COUNTSIGNALS']._serialized_end=292
  _globals['_FIREALARM']._serialized_start=294
  _globals['_FIREALARM']._serialized_end=363
# @@protoc_insertion_point(module_scope)
